language: php

php:
 - '5.6'
 - '7.3'

# Commands to be run before your environment runs.
before_script:
 - composer self-update
 - composer update --no-interaction

# Commands you want to run that will verify your build.
script: ./phpunit --coverage-clover=coverage.xml --testsuite=all_tests
